### ISSUE TITLE
workaround: using model on less than 12GB GPU 

### ISSUE THREAD

**Issue by eps696** [facebookresearch/pifuhd#4]
decreasing `intervals` value [here](https://github.com/facebookresearch/pifuhd/blob/8990c2e635d1f0e6f4317d3d42c2d900a895803c/apps/recon.py#L68) eliminates OOM error on lower grade GPUs
`intervals=50000` made it run on 8gb geforce 1080

**Comment by shunsukesaito** [comment]
I have updated the code accordingly. Thanks for the suggestion!!

**Comment by eps696** [comment]
@shunsukesaito it seems you have changed only readme, but not the code itself (with current interval-100000 it won't run on 8gb)

**Comment by shunsukesaito** [comment]
Oh, I changed interval but not num_sample. Now it should be corrected. Thank you!

**Comment by gormonn** [comment]
Hello! Great job!
I read this topic, however it seems that this is not enough for my GeForce GTX 1650 6GB graphics card. I played with this value, but still get an error:
```RuntimeError: CUDA out of memory. Tried to allocate 256.00 MiB (GPU 0; 5.80 GiB total capacity; 4.37 GiB already allocated; 123.31 MiB free; 146.48 MiB cached)```
It's about the size of the model, right?

Does anyone have any suggestions on how to reduce GPU memory requirements?

**Comment by eps696** [comment]
@gormonn unfortunately 6gb is below limit for the network itself (just checked on 6gb 1060). 
you may try debugging it (following the error messages) and delete unnecessary variables as soon as it's not needed anymore (maybe also followed by `torch.cuda.empty_cache()`). this would free some memory; it helped in quite a few other cases with torch for me.
